### ISSUE TITLE
Support for comas between arguments (so log calls with arguments can span one line, instead of several)

### ISSUE THREAD

**Issue by d4h0** [shakacode/rescript-logger#37]
Hi,

Thanks for building `rescript-logger`, it looks pretty neat!

I noticed that `%log.info("foo" ("bar", 42))` leads to the error `This expression has type string. It is not a function.`.

Instead, we have to put all arguments of the macro on a separate line:

```rescript
%log.info(
  "Login"
  ("loginUrl", loginUrl))
```

I think, that just adds unnecessary verbosity, and I'm wondering if "single-line-logging-with-arguments" can somehow be supported. For example, by allowing commas between arguments: `%log.info("foo", ("bar", 42))`.

My current workaround is, to use template strings, instead of the built-in 'argument' feature:

```rescript
%log.info(`foo bar=${42 -> Js.String.make}`)
```

...however, that isn't perfect, either.

**Comment by d4h0** [comment]
Oops, nevermind. I just noticed, that the Reason examples have semicolons between arguments, and that that works with ReScript, too:

```rescript
%log.info("foo"; ("bar", 42))
```

I think, it would be good to add such an example to the docs.

**Comment by alexfedoseev** [comment]
Formatter would remove these semicolons, though?

AFAIR we can't do anything about it on the lib level. This discussion/issue belongs to the rescript's syntax repo.

**Comment by d4h0** [comment]
> Formatter would remove these semicolons, though?

Really? I have not set up the formatter for my editor, so far.

I just tested it, and you are right. That's too bad.

> AFAIR we can't do anything about it on the lib level. This discussion/issue belongs to the rescript's syntax repo.

Would it be possible to support comas between arguments, as I proposed initially?

The formatter probably wouldn't treat comas as it does semicolons, right?

**Comment by alexfedoseev** [comment]
@d4h0 The lib doesn't define the syntax. We take AST and give back AST. We can't change the syntax, unfortunately.

**Comment by d4h0** [comment]
That's too bad. I currently only know the macro system of Rust, and this would be easy there.

Anyway, thanks for your quick responses, @alexfedoseev!

**Comment by alexfedoseev** [comment]
OCaml PPX is more like procedural macros in Rust: it receives a token stream and outputs a token stream, but the token stream is general Rust syntax that this kind of macro can't control. OCaml doesn't have anything like `macro_rules!`.
